// Generated by CoffeeScript 1.3.3
(function() {

  requirejs.config({
    shim: {
      "d3": {
        exports: "d3"
      }
    },
    paths: {
      "d3": "//d3js.org/d3.v3.min",
      "jquery": "//code.jquery.com/jquery-1.9.1.min",
      "socket.io": "/socket.io/socket.io"
    }
  });

  require(["d3", "vis/major-categories", "jquery", "socket.io"], function(d3, MajorCategories, $, io) {
    var majors, socket;
    majors = new MajorCategories($("#svg-holder"));
    socket = io.connect("/");
    socket.on("tweet", function(data) {
      return majors.receiveAddition(data);
    });
    return socket.on("initialData", function(data) {
      return majors.setInitials(data);
    });
  });

}).call(this);
